### ISSUE TITLE
share link broken (thanks github!)

### ISSUE THREAD

**Issue by ianfitzpatrick** [increpare/tinychoice#2]
Clicking share link for tinychoice game results in following 401 response from github's server:

{
  "message": "Requires authentication",
  "documentation_url": "https://developer.github.com/v3/gists/#create-a-gist"
}

I'm guessing they removed anonymous gist posts from their API?

I know tinychoice is three years old, but just in case you are interested in fixing it (or maybe just removing the share link).

**Comment by increpare** [comment]
yep, it's know. i've been very very lazy :/  sorry. thanks for the report
:)  I didn't think anyone ever used this even...

https://github.com/increpare/PuzzleScript/issues/431

2018-04-16 16:41 GMT+02:00 Ian Fitzpatrick <notifications@github.com>:

**Comment by ianfitzpatrick** [comment]
Ah gotcha, yeah that's never gonna get fixed then. Closing'er out!

PS why do you make so much awesome stuff, you are the best.

**Comment by increpare** [comment]
no no, it might get fixed!  hopefully will! :)
